
---
connection_info:
  dbname: newoti
  user: pguser
tables:
  curatorstudytable: curator_study_map
  treeotutable: tree_otu_map
  otutable: otu
  curatortable: curator
  treetable: tree
  studytable: study
treeginindex: tree_ix_jsondata_gin
studyginindex: study_ix_jsondata_gin
taxonomy: /Users/karen/Documents/opentreeoflife/data/ott2.9/
